[package]
name = "dioxus-toast"
version = "0.1.7"
authors = ["YuKun Liu <mrxzx.info@gmail.com>"]
repository = "https://github.com/mrxiaozhuox/dioxus-toast"
license = "MIT"
description = "Add toast support in your dioxus project"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["desktop"]

desktop = ["tokio", "dioxus/desktop"]

web = ["gloo-timers", "dioxus/web"]

[dependencies]
chrono = { version = "0.4.19", features = ["wasmbind"] }
dioxus = { version = "0.2.4", features = ["fermi"] }
tokio = { version = "1.17.0", features = ["time"], optional = true }
gloo-timers = { version = "0.2.3", features = ["futures"], optional = true }

[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
